# -*- coding: utf-8 -*-
"""langgraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZgo76PA4PHn6hP4wXG6WVqSCcTU1QIp
"""

!pip install -q \
langgraph \
langchain-core \
langchain-community \
gradio \
huggingface_hub

from typing import TypedDict

from langgraph.graph import StateGraph, END

from huggingface_hub import InferenceClient

HF_TOKEN = "Enter_Your_HF_API_KEY"

client = InferenceClient(
    model="meta-llama/Llama-3.1-8B-Instruct",
    token=HF_TOKEN
)

def generate_response(prompt):

    response = client.chat_completion(
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        max_tokens=500
    )

    return response.choices[0].message.content

class CareerState(TypedDict):
    name: str
    email: str
    phone: str
    age: str
    education: str
    interests: str
    skills: str
    experience: str
    goal: str
    linkedin: str

    analysis: str
    advice: str
    roadmap: str
    resume_content: str

def generate_resume(state):
    prompt = f"""
    Generate a professional resume for the following individual.
    Ensure the resume is well-structured and highlights relevant information.

    Name: {state['name']}
    Email: {state['email']}
    Phone: {state['phone']}
    Age: {state['age']}

    Education:
    {state['education']}

    Interests:
    {state['interests']}

    Skills:
    {state['skills']}

    Experience:
    {state['experience']}

    Career Goal:
    {state['goal']}
    LinkedIn Profile: {state['linkedin']}

    Please provide the resume content in a clear, markdown-formatted text.
    """

    result = generate_response(prompt)

    return {
        "resume_content": result
    }

def career_advice(state):

    prompt = f"""
    Based on this analysis:

    {state['analysis']}

    Provide career advice.
    """

    result = generate_response(prompt)

    return {
        "advice": result
    }

def learning_roadmap(state):

    prompt = f"""
    Goal:

    {state['goal']}

    Create a 3 month roadmap.
    """

    result = generate_response(prompt)

    return {
        "roadmap": result
    }

builder = StateGraph(CareerState)

builder.add_node("generate_resume", generate_resume)

builder.set_entry_point("generate_resume")

builder.add_edge("generate_resume", END)

graph = builder.compile()

import tempfile

def run_agent(name, email, phone, age, education, interests, skills, experience, goal, linkedin):

    result = graph.invoke(
        {
            "name": name,
            "email": email,
            "phone": phone,
            "age": age,
            "education": education,
            "interests": interests,
            "skills": skills,
            "experience": experience,
            "goal": goal,
            "linkedin": linkedin
        }
    )

    resume_markdown = result['resume_content']

    # Save the resume content to a temporary file
    with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.md', encoding='utf-8') as tmp_file:
        tmp_file.write(resume_markdown)
        file_path = tmp_file.name

    # Return both the markdown content and the file path
    return resume_markdown, file_path

import gradio as gr

demo = gr.Interface(
    fn=run_agent,
    inputs=[
        gr.Textbox(label="Name"),
        gr.Textbox(label="Email"),
        gr.Textbox(label="Phone"),
        gr.Textbox(label="Age"),
        gr.Textbox(label="Education", lines=3, placeholder="e.g., Bachelor's in Computer Science, University Name, Year"),
        gr.Textbox(label="Interests", placeholder="e.g., AI, Machine Learning, Web Development, Hiking"),
        gr.Textbox(label="Skills", lines=3, placeholder="e.g., Python, TensorFlow, React, SQL, Project Management"),
        gr.Textbox(label="Experience", lines=5, placeholder="e.g., Company Name, Role, Dates, Key Achievements"),
        gr.Textbox(label="Career Goal", placeholder="e.g., To become a Senior AI Engineer"),
        gr.Textbox(label="LinkedIn Profile", placeholder="e.g., linkedin.com/in/yourprofile")
    ],
    outputs=[gr.Markdown(label="Generated Resume"), gr.File(label="Download Resume")],
    title="<h1 style='text-align: center;'>📄 LangGraph AI Resume Generator 🚀</h1>",
    description="<p style='text-align: center;'>Enter your details below to generate a professional resume. You can then download the generated resume in Markdown format.</p>",
    theme=gr.themes.Soft(), # Applying a softer theme
    allow_flagging="never"
)

demo.launch(share=True, debug=True)

