# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRAfZ1-I_wTuMSOR2WqUIdRYbJ0Ec_dk
"""

# -*- coding: utf-8 -*-
import gradio as gr
from huggingface_hub import InferenceClient

# Initialize the Hugging Face InferenceClient
# WARNING: Keep your API key secret! Do not share it in public forums.
# Please replace "YOUR_HUGGING_FACE_API_KEY_HERE" with your actual Hugging Face API key.
client = InferenceClient(
    api_key="YOUR_HUGGING_FACE_API_KEY_HERE"
)

# Define the text-to-image model to use
TEXT_TO_IMAGE_MODEL = "black-forest-labs/FLUX.1-dev"

def generate_image(prompt):
    """
    Handles the text-to-image generation request.
    """
    if not prompt:
        gr.Warning("Please enter a prompt to generate an image.")
        return None

    try:
        # Call the text-to-image API
        # The client.text_to_image method returns a PIL Image object
        image = client.text_to_image(
            prompt=prompt,
            model=TEXT_TO_IMAGE_MODEL,
            negative_prompt="blurry, bad quality, low resolution, bad anatomy",
            width=768,
            height=768,
        )
        return image
    except Exception as e:
        print(f"Error during image generation: {e}")
        gr.Warning(f"An error occurred: {e}. Please try again.")
        return None

# --------------------------
# GRADIO UI BUILDER
# --------------------------
with gr.Blocks(theme='soft') as demo:
    gr.Markdown(
        """
        <div style="text-align: center; padding: 20px;">
            <h1>🎨 Text-to-Image Generator Project</h1>
            <p>Enter a prompt and watch the AI bring your words to life!</p>
        </div>
        """
    )

    with gr.Row():
        with gr.Column(scale=2):
            prompt_input = gr.Textbox(
                label="Image Prompt",
                placeholder="A cat riding a bicycle on the moon...",
                lines=3
            )
            generate_btn = gr.Button("Generate Image 🚀", variant="primary")
            clear_btn = gr.ClearButton([prompt_input], value="🗑️ Clear Prompt")
        with gr.Column(scale=1):
            output_image = gr.Image(label="Generated Image", type="pil", height=400)

    # --------------------------
    # EVENT LISTENERS
    # --------------------------
    generate_btn.click(
        fn=generate_image,
        inputs=[prompt_input],
        outputs=[output_image]
    )

    # You can also trigger generation by pressing Enter in the textbox
    prompt_input.submit(
        fn=generate_image,
        inputs=[prompt_input],
        outputs=[output_image]
    )

# Launch the interface
if __name__ == "__main__":
    demo.launch(share=True)